### ISSUE TITLE
footer issue

### ISSUE THREAD

**Issue by bhardwajhimanshu2515** [mosope02/bitsofco.de#1]
You forget to close a div before starting footer, so close the div.

**Comment by mosope02** [comment]
Thanks so much ☺️

**Comment by mosope02** [comment]
I've checked your solution and it worked 😃.
I'm so thankful.

**Comment by bhardwajhimanshu2515** [comment]
Your welcome brother, try to code in Visual Studio Code and these types of errors will not occur there.
